### ISSUE TITLE
Bug: Newly created `oclif generate` projects cannot build/compile (Typescript errors)

### ISSUE THREAD

**Issue by jmealo** [oclif/oclif#1087]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Follow documentation for creating a new project.

```
npm run build

> new-project@0.0.0 build
> shx rm -rf dist && tsc -b

src/commands/hello/index.ts:3:22 - error TS2417: Class static side 'typeof Hello' incorrectly extends base class static side 'typeof Command'.
  Types of property 'args' are incompatible.
    Type '{ name: string; description: string; required: boolean; }[]' is not assignable to type 'ArgInput<{ [arg: string]: any; }>'.
      Index signature for type 'string' is missing in type '{ name: string; description: string; required: boolean; }[]'.

3 export default class Hello extends Command {
                       ~~~~~

src/commands/hello/index.ts:19:44 - error TS2345: Argument of type 'typeof Hello' is not assignable to parameter of type 'Input<{ from: string; }, { [flag: string]: any; }, unknown[]>'.
  Types of property 'args' are incompatible.
    Type '{ name: string; description: string; required: boolean; }[]' is not assignable to type 'Arg<unknown, CustomOptions>[]'.
      Type '{ name: string; description: string; required: boolean; }' is not assignable to type 'Arg<unknown, CustomOptions>'.
        Type '{ name: string; description: string; required: boolean; }' is missing the following properties from type '{ options?: unknown[] | undefined; defaultHelp?: unknown; input: string[]; default?: unknown; parse: ArgParser<unknown, CustomOptions>; }': input, parse

19     const {args, flags} = await this.parse(Hello)
                                              ~~~~~

src/commands/hello/index.ts:21:28 - error TS2339: Property 'person' does not exist on type 'unknown[]'.

21     this.log(`hello ${args.person} from ${flags.from}! (./src/commands/hello/index.ts)`)
                              ~~~~~~

src/commands/hello/world.ts:3:22 - error TS2417: Class static side 'typeof World' incorrectly extends base class static side 'typeof Command'.
  Types of property 'args' are incompatible.
    Type 'never[]' is not assignable to type 'ArgInput<{ [arg: string]: any; }>'.
      Index signature for type 'string' is missing in type 'never[]'.

3 export default class World extends Command {
                       ~~~~~


Found 4 errors.

% node -v
v18.13.0
```

What is the expected behavior?
------------------------------
On Mac OS 12.6.2, using Node 18.13.0, and Typescript 4.94, I expect it to be possible to follow the new project generation script to get a project that can build successfully.

**Comment by mdonnalley** [comment]
@jmealo Thanks for posting this issue. I just pushed an update to the [template repo](https://github.com/oclif/hello-world) that should fix this. I'm going to close the issue for now but please feel free to reopen it if you continue to have the issue

**Comment by jmealo** [comment]
@mdonnalley: thanks, after upgrading to 3.6.1 using `npx oclif@` to trigger an update the generated hello world project compiles and runs properly.

**Comment by jameshfisher** [comment]
@mdonnalley I'm still getting this error. Here's what I ran:

```
$ npx oclif generate command deploy

     _-----_     ╭──────────────────────────╮
    |       |    │    Adding a command to   │
    |--(o)--|    │    foobar-cli Version:   │
   `---------´   │           3.6.1          │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

   create src/commands/deploy.ts

No change to package.json was detected. No package manager install will be executed.
```

It created the following file:

```
import {Command, Flags} from '@oclif/core'

export default class Deploy extends Command {
  static description = 'describe the command here'

  static examples = [
    '<%= config.bin %> <%= command.id %>',
  ]

  static flags = {
    // flag with a value (-n, --name=VALUE)
    name: Flags.string({char: 'n', description: 'name to print'}),
    // flag with no value (-f, --force)
    force: Flags.boolean({char: 'f'}),
  }

  static args = [{name: 'file'}]

  public async run(): Promise<void> {
    const {args, flags} = await this.parse(Deploy)

    const name = flags.name ?? 'world'
    this.log(`hello ${name} from /Users/jim/dev/jameshfisher/foobar-cli/src/commands/deploy.ts`)
    if (args.file && flags.force) {
      this.log(`you input --force and --file: ${args.file}`)
    }
  }
}
```

I then get the error:

```
$ npm run build

> foobar-cli@0.0.0 build
> shx rm -rf dist && tsc -b

src/commands/deploy.ts:3:22 - error TS2417: Class static side 'typeof Deploy' incorrectly extends base class static side 'typeof Command'.
  Types of property 'args' are incompatible.
    Type '{ name: string; }[]' is not assignable to type 'ArgInput<{ [arg: string]: any; }>'.
      Index signature for type 'string' is missing in type '{ name: string; }[]'.

3 export default class Deploy extends Command {
                       ~~~~~~

src/commands/deploy.ts:20:44 - error TS2345: Argument of type 'typeof Deploy' is not assignable to parameter of type 'Input<{ name: string | undefined; force: boolean; }, { [flag: string]: any; }, unknown[]>'.
  Types of property 'args' are incompatible.
    Type '{ name: string; }[]' is not assignable to type 'Arg<unknown, CustomOptions>[]'.
      Type '{ name: string; }' is not assignable to type 'Arg<unknown, CustomOptions>'.
        Type '{ name: string; }' is missing the following properties from type '{ options?: unknown[] | undefined; defaultHelp?: unknown; input: string[]; default?: unknown; parse: ArgParser<unknown, CustomOptions>; }': input, parse

20     const {args, flags} = await this.parse(Deploy)
                                              ~~~~~~

src/commands/deploy.ts:24:14 - error TS2339: Property 'file' does not exist on type 'unknown[]'.

24     if (args.file && flags.force) {
                ~~~~

src/commands/deploy.ts:25:54 - error TS2339: Property 'file' does not exist on type 'unknown[]'.

25       this.log(`you input --force and --file: ${args.file}`)
                                                        ~~~~


Found 4 errors.
```

**Comment by jmealo** [comment]
Try npx oclif@ to force upgrade.

**Comment by mon-jai** [comment]
@jmealo I am getting this error too.

The project's template has been updated, but the command template still contains error.

https://github.com/oclif/oclif/blob/fb51cedd36d3b164bab772eb3597d8305cbf8a6c/templates/src/command.ts.ejs#L18
