### ISSUE TITLE
Error: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by yatryan** [oclif/oclif#350]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
When building a project with a Typescript version less than 3.7, build fails with an error
```
ERROR in ../node_modules/@oclif/command/lib/command.d.ts:48:9 - error TS1086: An accessor cannot be declared in an ambient context.

48     get ctor(): typeof Command;
           ~~~~

error Command failed with exit code 1.
```
This appears to be happening since v1.16.0 (Breaking change introduced in #343). Previous version of oclif v1.15 does not have this issue (as typescript is an earlier version).

What is the expected behavior?
------------------------------
Build should succeed. I'm not sure if typescript can be downgraded, or at least a Breaking Change be noted in the changelog, etc.

oclif v1.16.0
MacOS 10.15.4

**Comment by yatryan** [comment]
Ah, I should open this in the correct repo.. https://github.com/oclif/command
